import {
  Activity,
  Mail,
  List,
  Image,
  FileText,
  MessageSquare,
  BarChart3,
  MapPin,
  Search,
  Layout,
  Globe,
  Info,
  UserCircle,
  Cpu,
  Heart,
  Settings2,
  HelpCircle,
  Images,
} from 'lucide-react';

export const ADMIN_TABS = [
  { value: 'overview', icon: Activity, labelKey: 'admin.nav.overview', resource: 'dashboard', action: 'read' },
  { value: 'bookings', icon: Mail, labelKey: 'admin.nav.bookings', badgeKey: 'unreadBookings', resource: 'leads', action: 'read' },
  { value: 'services', icon: List, labelKey: 'admin.nav.services', resource: 'services', action: 'read' },
  { value: 'gallery', icon: Image, labelKey: 'admin.nav.gallery', resource: 'gallery', action: 'read' },
  { value: 'media', icon: Images, labelKey: 'admin.nav.media', resource: 'media', action: 'read' },
  { value: 'blog', icon: FileText, labelKey: 'admin.nav.blog', resource: 'blog', action: 'read' },
  { value: 'testimonials', icon: MessageSquare, labelKey: 'admin.nav.testimonials', resource: 'testimonials', action: 'read' },
  { value: 'faq', icon: HelpCircle, labelKey: 'admin.nav.faq', resource: 'faq', action: 'read' },
  { value: 'stats', icon: BarChart3, labelKey: 'admin.nav.stats', resource: 'dashboard', action: 'read' },
  { value: 'users', icon: UserCircle, labelKey: 'admin.nav.users', resource: 'users', action: 'read' },
  { value: 'contact', icon: MapPin, labelKey: 'admin.nav.contact', resource: 'dashboard', action: 'read' },
  { value: 'branding', icon: Image, labelKey: 'admin.nav.branding', resource: 'branding', action: 'read' },
  { value: 'seo', icon: Search, labelKey: 'admin.nav.seo', resource: 'seo', action: 'read' },
  { value: 'hero', icon: Layout, labelKey: 'admin.nav.hero', resource: 'hero', action: 'read' },
  { value: 'pages', icon: Globe, labelKey: 'admin.nav.pages', resource: 'pages', action: 'read' },
  { value: 'sobre', icon: Info, labelKey: 'admin.nav.sobre', resource: 'pages', action: 'read' },
  { value: 'settings', icon: Settings2, labelKey: 'admin.nav.settings', resource: 'settings', action: 'read' },
];

export const PAGES_SECTION_OPTIONS = [
  { key: 'home', labelKey: 'admin.pages_sections.home' },
  { key: 'servicos', labelKey: 'admin.pages_sections.servicos' },
  { key: 'blog', labelKey: 'admin.pages_sections.blog' },
  { key: 'contato', labelKey: 'admin.pages_sections.contato' },
  { key: 'resultados', labelKey: 'admin.pages_sections.resultados' },
  { key: 'footer', labelKey: 'admin.pages_sections.footer' },
  { key: 'service_detail', labelKey: 'admin.pages_sections.service_detail' },
  { key: 'blog_post', labelKey: 'admin.pages_sections.blog_post' },
  { key: 'labels', labelKey: 'admin.pages_sections.labels' },
];

export const SOBRE_SECTION_OPTIONS = [
  { key: 'hero', icon: Layout, labelKey: 'admin.sobre_sections.hero' },
  { key: 'doctor', icon: UserCircle, labelKey: 'admin.sobre_sections.doctor' },
  { key: 'wfi', icon: Globe, labelKey: 'admin.sobre_sections.wfi' },
  { key: 'about', icon: Info, labelKey: 'admin.sobre_sections.about' },
  { key: 'values', icon: Heart, labelKey: 'admin.sobre_sections.values' },
  { key: 'team', icon: List, labelKey: 'admin.sobre_sections.team' },
  { key: 'technology', icon: Cpu, labelKey: 'admin.sobre_sections.technology' },
];
